### ISSUE TITLE
录播跳转的小建议

### ISSUE THREAD

**Issue by U5ER-N4ME** [K-bai/csv-based-web-music-player#1]
录播跳转的时候，可以直接定位到时间：
https://www.bilibili.com/video/【BV号】?p=【分p】&t=【当前分p的时间（秒为单位）】
这样对观看可以更方便一点

以《水星记》为例，可以直接跳转到[https://www.bilibili.com/video/BV1tP4y1J7dt?p=2&t=5709](https://www.bilibili.com/video/BV1tP4y1J7dt?p=2&t=5709)

**Comment by K-bai** [comment]
感谢建议！已经加上啦！
