### ISSUE TITLE
browse_flag未初始化

### ISSUE THREAD

**Issue by U5ER-N4ME** [K-bai/csv-based-web-music-player#2]
browse_flag未初始化，因此所有用户均为首次打开状态（就算不是第一次打开），保存的歌单会被覆盖、歌曲分享链接无法跳转。

fix: 在`/src/js/utils.js`的`if_first_browse()`函数中的第一个if分支中添加`localStorage.setItem('browse_flag', '20220101')`
（应该能行吧，我没试，直接在控制台初始化了）

**Comment by K-bai** [comment]
我是傻逼 已修复

**Comment by U5ER-N4ME** [comment]
草，K-bai老师，我不允许你这么说自己
